// Generated by https://quicktype.io

import { CastMovie } from './Cast-Movie';

export interface CastDetails {
    id:          number;
    name:        string;
    gender:      string;
    profilePath: string;
    tmdbUrl:     string;
    movies:      CastMovie[];
}
