// Generated by https://quicktype.io

import { Review } from './Review';
import { Genre } from './Genre';
import { Trailer } from './Trailer';
import { Cast } from './Cast';

export interface MovieDetails {
    id:                     number;
    title:                  string;
    overview:               string;
    tagline:                string;
    budget:                 number;
    revenue:                number;
    imdbUrl:                string;
    tmdbUrl:                string;
    posterUrl:              string;
    backdropUrl:            string;
    originalLanguage:       string;
    releaseDate:            string;
    runTime:                number;
    price:                  number;
    rating:                 number;
    purchasedSuccessNumber: null;
    genres:                 Genre[];
    trailers:               Trailer[];
    casts:                  Cast[];
    reviews:                Review[];
}