// Generated by https://quicktype.io

export interface PagedObject<T> {
    pageIndex:       number;
    pageSize:        number;
    totalPages:      number;
    totalRowCount:   number;
    hasPreviousPage: boolean;
    hasNextPage:     boolean;
    data:            T[];
}